### ISSUE TITLE
Giving me exception of :(OS Error: No address associated with hostname, errno = 7)

### ISSUE THREAD

**Issue by navidanchitrali** [nonvanilla-shop/shopify_flutter#1]
I am providing the shop name like: verden-app.myshopify.com, and the storeFrontApiToken(from the private app which I have created), I have allowed read_write permission for all the options as well, help, please?
I am just running the given example and want to print data from my store

**Comment by corbs9** [comment]
Perhaps just try passing in: `verden-app` instead of `verden-app.myshopify.com` as the code in `shopify.dart` does the following:
```
Shopify._({
    required String shop,
    required String storeFrontApiToken,
    required StoreFrontApiVersion storeFrontApiVersion,
  })  : _url = Uri.parse(
            'https://$shop.myshopify.com/api/${storeFrontApiVersion.value}/graphql.json'),
        _storeFrontApiToken = storeFrontApiToken;
```
It will append `myshopify.com` to your shopname.

**Comment by navidanchitrali** [comment]
@corbs9  Thanks man! the code runs successfully by only adding the shop name i,e: verden-app
